---
- name: Jenkins
  hosts: jenkins-server
  become: yes
  become_method: sudo
  vars:
    jenkins_repo: "http://pkg.jenkins-ci.org/redhat/jenkins.repo"
    jenkins_key: "https://jenkins-ci.org/redhat/jenkins-ci.org.key"
    jenkins_home: "/var/lib/jenkins"
    jenkins_plugins:
      - hipchat
      - git
      - job-dsl
      - workflow-aggregator
      - workflow-cps
      - blueocean
      - github-oauth
      - saml
      - custom-tools-plugin
    jenkins_job_template: jobs.groovy.j2
    jenkins_seed_name: pipeline-seed
    jenkins_seed_template: seed-config.xml.j2
    jenkins_git_user: git
    jenkins_git_host: github.umn.edu
    jenkins_git_path: OIT-CRM
    jenkins_git_repositories:
      - Enterprise
      - Student
    node_repo: "https://rpm.nodesource.com/setup_8.x"
  roles:
    - java
    - git
    - jenkins
    - salesforce